-- MySQL Script generated by MySQL Workbench
-- 03/10/17 20:42:14
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema farmersMarketDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema farmersMarketDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `farmersMarketDB` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `farmersMarketDB` ;

-- -----------------------------------------------------
-- Table `farmersMarketDB`.`District`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `farmersMarketDB`.`District` ;

CREATE TABLE IF NOT EXISTS `farmersMarketDB`.`District` (
  `districtID` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `districtName` VARCHAR(255) NOT NULL COMMENT '',
  PRIMARY KEY (`districtID`)  COMMENT '')
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `farmersMarketDB`.`SubPrefecture`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `farmersMarketDB`.`SubPrefecture` ;

CREATE TABLE IF NOT EXISTS `farmersMarketDB`.`SubPrefecture` (
  `subPrefectureID` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `subPrefectureName` VARCHAR(65) NOT NULL COMMENT '',
  PRIMARY KEY (`subPrefectureID`)  COMMENT '')
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `farmersMarketDB`.`Region5`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `farmersMarketDB`.`Region5` ;

CREATE TABLE IF NOT EXISTS `farmersMarketDB`.`Region5` (
  `region5ID` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `region5Name` VARCHAR(15) NOT NULL COMMENT '',
  PRIMARY KEY (`region5ID`)  COMMENT '')
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `farmersMarketDB`.`Region8`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `farmersMarketDB`.`Region8` ;

CREATE TABLE IF NOT EXISTS `farmersMarketDB`.`Region8` (
  `region8ID` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `region8Name` VARCHAR(15) NOT NULL COMMENT '',
  PRIMARY KEY (`region8ID`)  COMMENT '')
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `farmersMarketDB`.`Neighborhood`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `farmersMarketDB`.`Neighborhood` ;

CREATE TABLE IF NOT EXISTS `farmersMarketDB`.`Neighborhood` (
  `neighborhoodID` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `neighborhoodName` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`neighborhoodID`)  COMMENT '')
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `farmersMarketDB`.`FarmerMarket`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `farmersMarketDB`.`FarmerMarket` ;

CREATE TABLE IF NOT EXISTS `farmersMarketDB`.`FarmerMarket` (
  `farmerMarketID` INT NOT NULL COMMENT '',
  `farmerMarketLongitude` INT NOT NULL COMMENT '',
  `farmerMarketLatitude` INT NOT NULL COMMENT '',
  `farmerMarketSetCens` VARCHAR(21) NOT NULL COMMENT '',
  `farmerMarketAreaP` VARCHAR(17) NOT NULL COMMENT '',
  `farmerMarketName` VARCHAR(65) NOT NULL COMMENT '',
  `farmerMarketRegister` VARCHAR(6) NOT NULL COMMENT '',
  `farmerMarketPublicPlace` VARCHAR(65) NOT NULL COMMENT '',
  `farmerMarketNumber` VARCHAR(15) NULL COMMENT '',
  `farmerMarketReference` VARCHAR(255) NULL COMMENT '',
  `districtID` INT NOT NULL COMMENT '',
  `subPrefectureID` INT NOT NULL COMMENT '',
  `region5ID` INT NOT NULL COMMENT '',
  `region8ID` INT NOT NULL COMMENT '',
  `neighborhoodID` INT NOT NULL COMMENT '',
  PRIMARY KEY (`farmerMarketID`)  COMMENT '',
  INDEX `fk_FarmerMarket_District_idx` (`districtID` ASC)  COMMENT '',
  INDEX `fk_FarmerMarket_SubPrefecture1_idx` (`subPrefectureID` ASC)  COMMENT '',
  INDEX `fk_FarmerMarket_Region51_idx` (`region5ID` ASC)  COMMENT '',
  INDEX `fk_FarmerMarket_Region81_idx` (`region8ID` ASC)  COMMENT '',
  INDEX `fk_FarmerMarket_Neighborhood1_idx` (`neighborhoodID` ASC)  COMMENT '')
ENGINE = MyISAM;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

